package ui.canva;

import javax.swing.*;
import java.awt.event.KeyEvent;

/**
 * @author Rodrigo
 * @date 01 mayo, 2024
 */
public class Vista extends JFrame {
    int ancho, alto;
    Serpiente serpiente;
    Fondo fondo;

    public Vista(String tituloVentana, int ancho, String dificultad) {
        super(tituloVentana);
        initComponents();

        this.ancho = ancho;
        this.alto = ancho;
        this.setSize(ancho + 40, alto + 60);

        this.setLocationRelativeTo(null); //ventana en el centro

        switch (dificultad) {
            case "facil":
                serpiente = new Serpiente(ancho, 20);
                fondo = new Fondo(ancho, 20);
                break;
            case "dificil":
                serpiente = new Serpiente(ancho, 10);
                fondo = new Fondo(ancho, 10);
                break;
        }
        this.add(serpiente);
        serpiente.setBounds(10, 10, ancho, alto);
        serpiente.setOpaque(false);//El panel de la serpiente esta encima del fondo, por lo tanto debe ser transparente

         //El fondo sera de 800 pixeles dividido en 30 cuadrados
        this.add(fondo);
        fondo.setBounds(10, 10, ancho, alto);

    }

    private void tecla(KeyEvent event) {

        switch (event.getKeyCode()) {
            case KeyEvent.VK_LEFT:
                if (!serpiente.getDir().equals("izq") && !serpiente.getDir().equals("der"))
                    serpiente.setCambiodir("izq");
                break;
            case KeyEvent.VK_RIGHT:
                if (!serpiente.getDir().equals("izq") && !serpiente.getDir().equals("der"))
                    serpiente.setCambiodir("der");
                break;
            case KeyEvent.VK_UP:
                if (!serpiente.getDir().equals("arr") && !serpiente.getDir().equals("aba"))
                    serpiente.setCambiodir("arr");
                break;
            case KeyEvent.VK_DOWN:
                if (!serpiente.getDir().equals("arr") && !serpiente.getDir().equals("aba"))
                    serpiente.setCambiodir("aba");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tecla(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, ancho, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, alto, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Vista vista = new Vista("Serpiente", 600, "dificil");

                vista.setVisible(true);
                vista.setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify
    // End of variables declaration


}


